### ISSUE TITLE
Is possible to integrate apache shiro to wisdom ?

### ISSUE THREAD

**Issue by hboumedane** [wisdom-framework/wisdom#427]
Hi,

I was wondering if you could create some plugin for apache shiro to get it to work with wisdom.
why apache shiro ? because it's a good security framework with a lot of functionality out of the box (BasicHttpAuthentification......).

**Comment by cescoffier** [comment]
If I remember correctly, someone did something like that. Ask on the google
group.

On 4 févr. 2015, at 14:20, hboumedane <notifications@github.com> wrote:

Hi,

I was wondering if you could create some plugin for apache shiro to get it
to work with wisdom.
why apache shiro ? because it's a good security framework with a lot of
functionality out of the box (BasicHttpAuthentification......).

—
Reply to this email directly or view it on GitHub
<https://github.com/wisdom-framework/wisdom/issues/427>.

**Comment by hboumedane** [comment]
yes , but i want to use apache shiro filter ? and i don't how to activate them with wisdom (wisdom has his own filters ), the exemple in google used only some realm (like jdbc)..

**Comment by cescoffier** [comment]
It’s probably using Servlet Filter which are not supported (and won’t as we are far from the servlet world), but nothing avoid to re-implement the filter as a Wisdom filter.

On 4 février 2015 at 16:12:25, hboumedane (notifications@github.com) wrote:

yes , but i want to use apache shiro filter ? and i don't how to activate them with wisdom (wisdom has his own filters ), the exemple in google used only some realm (like jdbc)..

**Comment by hboumedane** [comment]
ok i will try to extend wisdom filter , thanks for the advice .

**Comment by cescoffier** [comment]
did you implement the filter?

2015-02-17 11:21 GMT+01:00 hboumedane <notifications@github.com>:

**Comment by hboumedane** [comment]
yes i did and it's working thanks !!
