### ISSUE TITLE
wisdom:run should indicate problems with controllers

### ISSUE THREAD

**Issue by Kricket** [wisdom-framework/wisdom#428]
I'm just starting with wisdom. I got a simple controller up and running fine.

Next, I tried to inject configuration from a custom config file:

	@Requires(filter="(configuration.path=portals)")
	Configuration portalsConfig;

(I added a portals.conf to the configuration/ directory.) The result is that my Controller disappeared. Zero messages in the log indicating what might have gone wrong. It would be a lot easier if wisdom were to log why an object with all the fixings of a controller somehow didn't make the final cut.

**Comment by cescoffier** [comment]
The monitor gives you hints, but so far it does not managed "Configuration" (the support is quite new).

In your case, you need to `include` (using HOCON include) `portals.conf` in the `application.conf`. The `configuration.path` is not the file path but the path in the configuration tree.

**Comment by Kricket** [comment]
Ah, OK...thanks for the hint with the configuration setup...

Still, the real issue here is just having some sort of log message when a Controller fails to initialize. In this case, something like "Couldn't create XYZController: unable to inject "portalsConfig": ABCException...." would be helpful.

**Comment by cescoffier** [comment]
Yes we can add a 'doctor', but as Wisdom is dynamic, it may report expected invalidity

**Comment by Kricket** [comment]
Pardon my ignorance, but I didn't follow you there...
You're saying that having some Controllers work and others not, is a normal part of the application lifecycle?

**Comment by cescoffier** [comment]
Hi,

I understand this is kind of weird, because that's what make Wisdom unique. Wisdom is dynamic, meaning that your application is able to react to the availability or unavailability of _services_. This reaction is generally reflected as a publication or a withdrawal of another service. This mechanism can be illustrated with _dominos_: if one domino falls, it triggers the fall of the dependent dominos. If the fell domino is up again - and it's where the metaphor starts to be weird - all dependent dominos stand up again. 

So to come back to your issue, Wisdom does not consider an invalid controller as a necessarily bad thing. It may be expected because its dependencies are not satisfied yet, but this may change in the future. For instance, you can imagine a feature toggle, or a part of your application not completely done... That's why the Wisdom-Monitor gives you the reason behind the invalidity, and not the console.

However, we can add a `doctor` component that do an analysis, and give you some ideas in the console.

**Comment by Kricket** [comment]
OK. I did some reading up on OSGi and I think I get it better now...
