### ISSUE TITLE
Wisdom Monitor 0.7.1-SNAPSHOT present in wisdom-monitor.zip distribution 

### ISSUE THREAD

**Issue by magnet** [wisdom-framework/wisdom#441]
Routes are conflicting because the two bundles are present in the official distribution.

Only 0.7.0 should be present.

**Comment by cescoffier** [comment]
Which 'official' distribution ? The last release ?

Sent from my iPhone

On 13 févr. 2015, at 15:58, Simon Chemouil <notifications@github.com> wrote:

Routes are conflicting because the two bundles are present in the official
distribution.

Only 0.7.0 should be present.

—
Reply to this email directly or view it on GitHub
<https://github.com/wisdom-framework/wisdom/issues/441>.

**Comment by magnet** [comment]
http://search.maven.org/remotecontent?filepath=org/wisdom-framework/wisdom-monitor/0.7.0/wisdom-monitor-0.7.0.zip

It's too late for that release, but not for the next one ;) BTW the same issue was present in 0.6.4 and not in 0.6.5 :-).

**Comment by cescoffier** [comment]
Hum weird, good you notice it. Anyway a 0.7.1 release is planned.

Sent from my iPhone

On 13 févr. 2015, at 20:06, Simon Chemouil <notifications@github.com> wrote:

http://search.maven.org/remotecontent?filepath=org/wisdom-framework/wisdom-monitor/0.7.0/wisdom-monitor-0.7.0.zip

It's too late for that release, but not for the next one ;) BTW the same
issue was present in 0.6.4 and not in 0.6.5 :-).

—
Reply to this email directly or view it on GitHub
<https://github.com/wisdom-framework/wisdom/issues/441#issuecomment-74307823>
.

**Comment by cescoffier** [comment]
The main question is why did this happen....

**Comment by cescoffier** [comment]
Found the bug, it's in the release process. It's fixed in the 0.8.0.
