### ISSUE TITLE
[wisdom-raml] generation fails with some parameters

### ISSUE THREAD

**Issue by jetien** [wisdom-framework/wisdom#505]
with @Parameter and @PathParameter : infinite loading
with @Body : doesn't show the expected object

**Comment by barjo** [comment]
Hi @jetien can you provide an example of Paramater/PathParameter and Body params that fails.

**Comment by jetien** [comment]
Hi, I try with this method : 

 ```
@Route(method = GET, uri = "/testtest")
    public Result test(
                              // @Body String user,
                                 @FormParameter("fileItem") FileItem fileItem
                            // , @Parameter("isAdmin") boolean isAdmin
                               , @QueryParameter("test") Integer test
                            // , @PathParameter("fullInfos") Boolean fullInfos   ) {
        return ok();
    }
```

**Comment by barjo** [comment]
Thanks, I will try to reproduce and add it to the test cases.

**Comment by barjo** [comment]
Hi, I just add some test cases. The problem is that you use PathParam and Parameter without having it declare in your uri. 

```
@Route(method= GET, uri = /test/{isAdmin})
public Result test(@Parameter("isAdmin") boolean isAdmin)
```

If you don't have the corresponding uri parameter in your uri/path, in that case `{isAdmin}`, the raml javascript monitor will fail. 

One thing I can do is to log an error during the parsing, to say that you declare a Parameter/PathParameter without declaring it in the uri/path. 

Regarding the Body, you can specify the content-type of your Body thanks to the `accepts` attribute of your route. For example: 

``` 
@Route(method = HttpMethod.GET, uri = "/test",accepts = "text/plain")
```
